#!/bin/bash
#KWVH

su

install
{
clear
echo "***INSTALLER***"
echo -n "Package name: "
read package
echo "...installing $package"
apt-get install $package
}

install

resp0="y"

while [ "$resp1" = "y" ]; do
	echo -n "Run again(y/n)? "
	read resp1
	if [ "$resp1" = "y" ]; then install; fi
done
