#!/bin/bash
#KWVH

su

uninstall
{
clear
echo "***UNINSTALLER***"
echo -n "Package name: "
read package
echo "...uninstalling $package"
apt-get remove $package
}

uninstall

resp0="y"

while [ "$resp1" = "y" ]; do
	echo -n "Run again(y/n)? "
	read resp1
	if [ "$resp1" = "y" ]; then uninstall; fi
done
